steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--file",
        "qa.dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/qa-aiways:$COMMIT_SHA",
        ".",
      ]
  # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/qa-aiways:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "qa-aiways"
      - "--image"
      - "gcr.io/$PROJECT_ID/qa-aiways:$COMMIT_SHA"
      - "--region"
      - "us-east1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
